version: '3.8'

services:
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-elasticsearch-server
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
    networks:
      - mcp-network
    stdin_open: true
    tty: true
    command: /bin/bash

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

volumes:
  elasticsearch-data:
    driver: local